DROP TABLE IF EXISTS PRICES;

CREATE TABLE PRICES (
  BRAND_ID INT,
  START_DATE TIMESTAMP,
  END_DATE TIMESTAMP,
  PRICE_LIST INT,
  PRODUCT_ID INT,
  PRIORITY INT,
  PRICE DOUBLE,
  CURR VARCHAR(10)
);
